services:
#    front.example:
#        class: FrontBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
        app.form.registration:
            class: FrontBundle\Form\UserType
            tags:
                - { name: form.type, alias: user_registration }
