front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"