<?php

namespace FrontBundle\Repository;

/**
 * DisponiiliteeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponiiliteeRepository extends \Doctrine\ORM\EntityRepository
{
}
